### ISSUE TITLE
There is only "self.transformerlayer = TransformerEncoderLayer" in "class TransformerUnit", but no "TransformerDecoderLayer".

### ISSUE THREAD

**Issue by sgtscu** [something678/TodKat#11]
Hi there, I found TransformerDecoderLayer is not used in the code repo, and I wonder why this is different from the Transformer Encoder-Decoder Classifier in the paper. Thanks!!!

**Comment by something678** [comment]
Hi there, thanks for the interest! Looks like the decoder is not prominent to bring improvements, so we removed it to make the model smaller. But the decoder version will be sent to you to add to the understanding of the model.
