### ISSUE TITLE
model path error

### ISSUE THREAD

**Issue by rungjoo** [something678/TodKat#12]
I'm trying to run the training code. So I uncommented the lines and ran the code.
I got the following error:
![image](https://user-images.githubusercontent.com/48037590/150317903-2ce079fb-88c6-4508-8565-2da7c88c079d.png)

After checking the cause, model_path is set as follows.
tokenizer_name = '../datasets/topic-language-model-iemocap'

Is this the intended code? There is no folder on github for the model. Isn't RoBERTa's pretraeind path roberta-{size}?

thank you.

**Comment by squid-ball** [comment]
Did you find the solution for this. Facing the same issue.

**Comment by something678** [comment]
Hi, you need to download the save.zip and place the 'topic-language-model-iemocap' folder in the '../datasets/' directory.

**Comment by rungjoo** [comment]
No. I can't solve this...

2022년 3월 12일 (토) 오후 12:38, squid-ball ***@***.***>님이 작성:
