### ISSUE TITLE
Where is the point network？

### ISSUE THREAD

**Issue by RenzeLou** [something678/TodKat#9]
Hello, authors,

First of all, Thank you for your interesting work! 

I note you have mentioned in your paper that you utilize the point network to select the knowledge coming from the pre-trained model. I need this part of the function, however, I can't find this corresponding code in your repository.

Best!

**Comment by something678** [comment]
Hi there, the pointer network is for automatically choosing the knowledge base. Once the knowledge base is chosen seems you can stick to the knowledge and no longer need to make a trade-off between different knowledge bases. I will open up a new branch to show you the difference. Thanks for the interests!
